ckan/ckan-docker-base

datapusher/Dockerfile, datapusher/Makefile
It's best to have the version to build defined in one single place, in this case the Makefile rather than across different files.
When there's a new version we can update the Makefile and if some builds the image without using `make build` they'll always get the `master` branch.
Also bumps the build version to 0.0.19
=> Simplify DataPusher build scripts, bump to latest version

ckan-2.10/base/Dockerfile
Taken the `pip3 install -r requirement-setuptools.txt && \` line out of the 2.10 Dockerfile
=> Remove requirement-setuptools from the 2.10 image

README.md
I believe this is the current convention and what the Makefiles will generate.
I also removed any non-latest patch release to encourage users to use the latest one.
=> Fix image tags in README

ckan-2.10/base/Dockerfile
That is preventing the 2.10 image from being built.
More details in https://github.com/ckan/ckan/pull/7864
This can be removed once the above is merged and CKAN 2.10.2 released
=> Add workaround for pyyaml/cython requirements issue

ckan-2.10/base/Dockerfile, ckan-2.10/base/setup/start_ckan.sh, ckan-2.10/dev/setup/start_ckan_development.sh, ckan-2.9/base/Dockerfile
As discussed in ckan/ckan-docker#95
Remove datapusher from default plugin list env var and remove setup commands from the entrypoint scripts
(start_ckan.sh/start_ckan_development.sh)
Sadly we still need the one to add a temporary value on the api token config option, otherwise all `ckan` commands will fail, but at least we only run it if datapusher is listed in CKAN__PLUGINS
=> Decouple datapusher from init scripts

ckan-2.10/base/Dockerfile, ckan-2.9/base/Dockerfile
The new TZ changes in https://github.com/ckan/ckan-docker-base/pull/31 needed to be updated for the image to build. Plus the CKAN 2.9 build for pyyaml needed some extra workaround to build
Built all images and pushed to DockerHub
=> Updates to tz and pyyaml

ckan-2.10/base/setup/prerun.py, ckan-2.9/base/setup/prerun.py
We are still checking for the connection even when the ENV variables are not defined.
This causes some confusing logs since we are saying that we are not checking but "something" is being checked anyways.
```
[prerun] Plugins set.
[prerun] CKAN_DATASTORE_WRITE_URL not defined, not checking db
connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
Is the server running locally and accepting connections on that socket?
[prerun] Unable to connect to the database, waiting...
connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
Is the server running locally and accepting connections on that socket?
[prerun] Unable to connect to the database, waiting...
connection to server on socket …
```
=> Do not check dbs if ENV variables are not defined

ckan-2.10/base/Makefile, ckan-2.10/dev/Makefile, ckan-2.9/base/Makefile, ckan-2.9/dev/Makefile
Fixes https://github.com/ckan/ckan-docker-base/issues/36
There is a requirement to use alternative tags for the CKAN images ie: `major. minor` version (eg: `2.10`) for the ckan/ckan-base and ckan/ckan-dev images
=> Update Makefiles with alt tags, push to repo

README.md, ckan-2.10/base/Dockerfile, ckan-2.10/base/Makefile, ckan-2.10/dev/Dockerfile, ckan-2.10/dev/Makefile, ckan-2.9/base/Dockerfile, ckan-2.9/base/Makefile, ckan-2.9/dev/Dockerfile, ckan-2.9/dev/Makefile
- Build ckan 2.10.3 and 2.9.10 images
- Push to DockerHub
- Tested containers built off 2.10.3 base and dev images
- Tested containers built off 2.9.10 base and dev images
=> Build ckan 2.10.3 and 2.9.10 images

datapusher/Dockerfile
`libmagic` is a `messytables` requirement.
I'm getting this error in datapusher
`apk` packages installed with `--virtual` are removed with `apk del`
It looks like we need this Alpine package to be permanent.
=> Preserve libmagic

ckan-2.10/dev/setup/start_ckan_development.sh, ckan-2.9/dev/setup/start_ckan_development.sh, ckan-master/dev/setup/start_ckan_development.sh
supervisord is not ideal for a development server.
- if ckan restarts too quickly (e.g. accidental syntax error) supervisor will stop trying to restart the service
- if you want to run ckan from the shell (e.g. for pdb debugging) the start_ckan_development.sh script can't be interrupted with ^C or ^\ making it difficult to forcibly restart or cleanly shut down the container
I've replaced supervisor in the dev environments with a while loop and a short delay so we can see the traceback on restart.
=> use while loop for restarting dev

ckan-2.10/dev/setup/start_ckan_development.sh, ckan-2.9/dev/setup/start_ckan_development.sh, ckan-master/dev/setup/start_ckan_development.sh
Includes the changes from #49, please review that one first
Adds a new option `USE_DEBUGPY_FOR_DEV` that when set to `true` will install and run ckan under debugby so that VS Code can attach to the running process for remote debugging.
=> debugpy support for VS Code remote debugging

ckan-2.10/base/setup/prerun.py, ckan-2.9/base/setup/prerun.py, ckan-master/base/setup/prerun.py
on ckan master this also applies extension upgrades (like the required activities migration) whereas `db init` does not.
=> Upgrade db like the console text says

ckan-2.10/dev/setup/start_ckan_development.sh, ckan-2.9/dev/setup/start_ckan_development.sh, ckan-master/dev/setup/start_ckan_development.sh
ckan-docker-base has `ckan` and `ckanext-envvars` installed under `src` with additional packages installed under `src_extensions` (mapping to a local `src` directory, confusingly)
If you have a copy of `ckan` or `ckanext-envvars` in `src_extensions` they will be installed, but not completely because the entry points from the ckan-docker-base packages won't be updated.
This PR uninstalls any existing `src` package if a directory with the same name is in `src_extensions` so that the entry points for development versions of packages are updated correctly.
=> uninstall src packages found in src_extensions

ckan-2.10/dev/setup/start_ckan_development.sh, ckan-2.9/dev/setup/start_ckan_development.sh, ckan-master/dev/setup/start_ckan_development.sh
`pyproject.toml` is becoming more and more popular in Python packaging so it would be good if extensions using this approach are supported as well
Probably `pip install -e .` might be universal command for installing an extension no matter whether it's setup or pyproject based
=> Support dev extensions with "pyproject.toml"

ckan-master/base/Dockerfile
Since https://github.com/ckan/ckan/pull/7893 installing requirements from a local copy of ckan in `src` fails trying to uninstall `packaging`, which was installed a requirement of the system package `py3-gevent` (not via pip), so pip can't uninstall it.
AFAICT we don't use `py3-gevent` so I'm removing it and `uwsgi-gevent` from the install here.
=> fix for master packaging uninstall error

ckan-2.10/base/setup/start_ckan.sh, ckan-master/base/setup/start_ckan.sh, datapusher/Dockerfile, datapusher/Makefile
- Bump DataPusher version to **0.0.21**
- Listen on an IPv6 unspecified address for DataPusher and CKAN (rather than IPv4) [related issue](https://github.com/ckan/ckan-docker-base/issues/65)
- Set UTC timezone to get rid of warning messages
=> Bump DataPusher version (0.0.21) and DataPusher and CKAN to listen on ipv6 addresses

README.md, ckan-2.9/base/Dockerfile, ckan-2.9/base/Dockerfile.py3.9, ckan-2.9/base/Makefile, ckan-2.9/dev/Dockerfile.py3.9, ckan-2.9/dev/Makefile, ckan-2.9/dev/setup/start_ckan_development.sh
2.9 will soon stop being supported but hopefully this will help users transition to newer versions (both of CKAN and of the Docker images)
Had to use Python 3.9 because CKAN 2.9 is not 3.10 compatible
=> Add Debian-based Python images for CKAN 2.9 

ckan-2.9/dev/Dockerfile.py3.9
In CKAN **2.9** (**dev**) use `ckan/ckan-base:2.9.11-py3.9` for the base image (rather than `.py3.10`)
=> Update Dockerfile.py3.9 for CKAN 2.9 (dev)

ckan-2.11/Dockerfile, ckan-2.9/setup/install_src.sh
A couple of small updates:
- CKAN 2.11 - There is a duplication of lines in the Dockerfile that caused a problem building the images. The offending lines were removed
- CKAN 2.9 - the `install_src.sh` file is missing. I assume that this file is needed for CKAN 2.9
=> Simplify repo: updates

ckan-2.10/Dockerfile.py3.10, ckan-2.10/setup/supervisord.py3.conf, ckan-2.9/Dockerfile.py3.9, ckan-2.9/setup/supervisord.py3.conf
Although supervisor has been removed from 2.11 onward, it is still used in the 2.10 and 2.9 images. In #80 the supervisord.conf [was modified](https://github.com/ckan/ckan-docker-base/pull/80/files#diff-a9f3dc77dfb98b40d119163f7a8049572695f238c20380a6c9ca8e43c4a9daf3R4) to run the process as the newly created `ckan-sys` user, but this same conf file is used in the alpine image, where this user does not exist. Conversely, the 2.9 Python image includes the same file as the alpine one, so it doesn't use the new user.
This PR splits the files in two different versions so they use the appropriate user.
=> Fix supervisor conf file owners

.github/workflows/reusable-docker-publish.yml
Introduced in #92 
GitHub Actions performs a shallow clone that doesn't include all tags by default so this command:
LATEST_GIT_TAG=$(git describe --tags --abbrev=0)
Was failing with:
fatal: No names found, cannot describe anything.
This setting makes the checkout fetch the tags as well
=> Fetch tags in git checkout to fix publish workflows

.github/workflows/reusable-docker-publish.yml
`fetch-tags: true` in the checkout action does not work as expected and causes an error:
Error: fatal: Cannot fetch both 2704e6e918d2c70a4f44348e34618ef5146211b4
and refs/tags/v20241203 to refs/tags/v20241203
The issue is described in
https://github.com/actions/checkout/issues/1467
We will just fetch the tags manually
=> Fetch tags manually in publish workflow

ckan-2.10/setup/install_src.sh, ckan-2.10/setup/start_ckan_development.sh, ckan-2.11/Dockerfile, ckan-2.11/setup/install_src.sh, ckan-2.11/setup/start_ckan_development.sh, ckan-2.9/setup/install_src.sh, ckan-2.9/setup/start_ckan_development.sh
debugpy needs to be installed from the install script, and the `ckan` home directory `/srv/app` needs to be writable to install vscode inside the container (also useful for files like .bash_history when developing)
=> move debugpy install to install_src, writable home for dev

ckan-2.10/Dockerfile.py3.10, ckan-2.11/Dockerfile
patch is needed to deploy updates at runtime
for ckan/ckan-docker#168
=> Add apt install for patch

datapusher/Dockerfile
fixes: https://github.com/ckan/ckan-docker-base/issues/109
Explicitly installs `wget` system package as the alpine (preinstalled) wget command software does not seem to work correctly if DataPusher is running behind a proxy
NB: This will update the `ckan/ckan-base-datapusher:0.0.21` image so an accompanying ckan-docker repo PR should also be created as it currently uses `ckan/ckan-base-datapusher:0.0.20`
=> DataPusher explicitly installs wget

.github/workflows/build-and-test-2.11-pyver3.11.yml, .github/workflows/reusable-build-and-test.yml, README.md, build.sh, ckan-2.11/Dockerfile
The Python version is specified here: [PYTHON_VERSION](https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.11/PYTHON_VERSION.txt) When a new version of Python is required to build the base/dev images for CKAN 2.11 (and subsequent future versions...`2.12` etc) the new version (value) can be changed there and new images built based on that version of Python.
I have intentionally left out CKAN `2.10` and `2.9` as this would be messy as those versions have specific Dockerfiles based on the `python:<version>-slim-bookworm` base images
=> Parameterize python version for CKAN 2.11

.github/workflows/reusable-docker-publish.yml
Fixes: https://github.com/ckan/ckan-docker-base/issues/119
The Dockerfile for CKAN **2.11** now includes an  `ARG PYTHON_VERSION` line so any script or process using this file will need to pass a build-arg to it
`reusable-docker-publish.yml` has been updated to pass this parameter to the CKAN 2.11 Dockerfile
=> reusable-docker-publish.yml needs to send the python parameter to build CKAN 2.11

README.md, ckan-2.10/setup/start_ckan.sh, ckan-2.11/setup/start_ckan.sh, ckan-2.9/setup/start_ckan.sh
This PR resolves #114. It extends the bahavior of `start_ckan.sh` to allow both _overwriting_ and _extending_ the `uwsgi` command line args. The current behavior of `UWSGI_OPTS` env var remains untouched, so this won't affect users that already overwirte `UWSGI_OPTS`, or don't.
- In `start_ckan.sh` there is a new env var `DEFAULT_UWSGI_OPTS` that defines default options for `uwsgi`. This contains what was previously stored in `UWSGI_OPTS` in `start_ckan.sh`.
- If `UWSGI_OPTS` is set at runtime, `DEFAULT_UWSGI_OPTS` is overwritten with the content of `UWSGI_OPTS`.
- If the new env var `EXTRA_UWSGI_OPTS` is set at runtime, its content is appended to `UWSG_OPTS`.
- For `UWSGI_HARAKIRI` a default values of 60 is introduced.
If there is any place to document this, let me know, I can add …
=> Overwrite UWSGI_OPTS from ENV or adapt with EXTRA_UWSGI_OPTS
